### ISSUE TITLE
Open to collaboration?

### ISSUE THREAD

**Issue by msdrigg** [Michael-F-Bryan/lastpass#2]
Hey Michael,

I am interested in a lastpass interface for rust and I found your project. Would you be open to reviewing pull requests with enhancements/new features or should I fork this repository?

Scott

**Comment by Michael-F-Bryan** [comment]
I don't have much spare time these days, but if you are just wanting me to look over your code before merging then that's fine. Alternatively, I can add you to this repo as a collaborator.

**Comment by msdrigg** [comment]
I understand the time issue. I was planning to use this repository as part of a larger project to allow for seamless syncing of bitwarden and lastpass (and maybe other) password managers, but there were a few features that this library was missing (specifically fields). 

When I get around to creating that project, I will just open PR's with any positive changes. I don't think it's necessary to add me as a collaborator, but I would appreciate you looking over changes and offering any feedback. I am kinda new to rust and have only used it in one project so far
